name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x', '22.x']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: isol
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: forumapi_test

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install migrate and test
        run: |
          npm install
          npm run migrate:test up
          npm run test
        env:
          CI: true
          NODE_ENV: test
          HOST: localhost
          PORT: 5000
          PGHOST_TEST: localhost
          PGPORT_TEST: 5432
          PGUSER_TEST: isol
          PGPASSWORD_TEST: 123456
          PGDATABASE_TEST: forumapi_test
          ACCESS_TOKEN_KEY: secret
          REFRESH_TOKEN_KEY: terces
          ACCESS_TOKEN_AGE: 3600
